[package]
name = "nanopass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanopass-macro = { version = "0.1.0", path = "nanopass-macro" }
