[book]
authors = ["Alona Enraght-Moony"]
language = "en"
multilingual = false
src = "src"
title = "Angstropass Compiler Framework"

[output.html]
git-repository-url = "https://github.com/aDotInTheVoid/angstropass"
edit-url-template = "https://github.com/aDotInTheVoid/angstropass/edit/trunk/docs/{path}"
